/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeusAgendamentosRouteImport } from './routes/meus-agendamentos'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AgendarIndexRouteImport } from './routes/agendar/index'
import { Route as AgendarConfirmacaoRouteImport } from './routes/agendar/confirmacao'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated/app.agenda'
import { Route as AuthenticatedAppAgendamentosRouteImport } from './routes/_authenticated/app.agendamentos'
import { Route as AuthenticatedAppBarbeirosRouteImport } from './routes/_authenticated/app.barbeiros'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/app.configuracoes'
import { Route as AuthenticatedAppPagamentosRouteImport } from './routes/_authenticated/app.pagamentos'
import { Route as AuthenticatedAppRelatoriosRouteImport } from './routes/_authenticated/app.relatorios'
import { Route as AuthenticatedAppServicosRouteImport } from './routes/_authenticated/app.servicos'
import { Route as ApiWhatsappStatusRouteImport } from './routes/api/whatsapp/status'
import { Route as AuthenticatedAppClientesIndexRouteImport } from './routes/_authenticated/app.clientes.index'
import { Route as AuthenticatedAppClientesIdRouteImport } from './routes/_authenticated/app.clientes.$id'
import { Route as ApiPublicHooksAutomacoesRouteImport } from './routes/api/public/hooks/automacoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusAgendamentosRoute = MeusAgendamentosRouteImport.update({
  id: '/meus-agendamentos',
  path: '/meus-agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AgendarIndexRoute = AgendarIndexRouteImport.update({
  id: '/agendar/',
  path: '/agendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarConfirmacaoRoute = AgendarConfirmacaoRouteImport.update({
  id: '/agendar/confirmacao',
  path: '/agendar/confirmacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAgendamentosRoute =
  AuthenticatedAppAgendamentosRouteImport.update({
    id: '/agendamentos',
    path: '/agendamentos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBarbeirosRoute =
  AuthenticatedAppBarbeirosRouteImport.update({
    id: '/barbeiros',
    path: '/barbeiros',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPagamentosRoute =
  AuthenticatedAppPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRelatoriosRoute =
  AuthenticatedAppRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppServicosRoute =
  AuthenticatedAppServicosRouteImport.update({
    id: '/servicos',
    path: '/servicos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiWhatsappStatusRoute = ApiWhatsappStatusRouteImport.update({
  id: '/api/whatsapp/status',
  path: '/api/whatsapp/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppClientesIndexRoute =
  AuthenticatedAppClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClientesIdRoute =
  AuthenticatedAppClientesIdRouteImport.update({
    id: '/clientes/$id',
    path: '/clientes/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiPublicHooksAutomacoesRoute =
  ApiPublicHooksAutomacoesRouteImport.update({
    id: '/api/public/hooks/automacoes',
    path: '/api/public/hooks/automacoes',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/meus-agendamentos': typeof MeusAgendamentosRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/agendar/confirmacao': typeof AgendarConfirmacaoRoute
  '/agendar/': typeof AgendarIndexRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/agendamentos': typeof AuthenticatedAppAgendamentosRoute
  '/app/barbeiros': typeof AuthenticatedAppBarbeirosRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/pagamentos': typeof AuthenticatedAppPagamentosRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/servicos': typeof AuthenticatedAppServicosRoute
  '/api/whatsapp/status': typeof ApiWhatsappStatusRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/clientes/$id': typeof AuthenticatedAppClientesIdRoute
  '/api/public/hooks/automacoes': typeof ApiPublicHooksAutomacoesRoute
  '/app/clientes/': typeof AuthenticatedAppClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/meus-agendamentos': typeof MeusAgendamentosRoute
  '/agendar/confirmacao': typeof AgendarConfirmacaoRoute
  '/agendar': typeof AgendarIndexRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/agendamentos': typeof AuthenticatedAppAgendamentosRoute
  '/app/barbeiros': typeof AuthenticatedAppBarbeirosRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/pagamentos': typeof AuthenticatedAppPagamentosRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/servicos': typeof AuthenticatedAppServicosRoute
  '/api/whatsapp/status': typeof ApiWhatsappStatusRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/clientes/$id': typeof AuthenticatedAppClientesIdRoute
  '/api/public/hooks/automacoes': typeof ApiPublicHooksAutomacoesRoute
  '/app/clientes': typeof AuthenticatedAppClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/meus-agendamentos': typeof MeusAgendamentosRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/agendar/confirmacao': typeof AgendarConfirmacaoRoute
  '/agendar/': typeof AgendarIndexRoute
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/agendamentos': typeof AuthenticatedAppAgendamentosRoute
  '/_authenticated/app/barbeiros': typeof AuthenticatedAppBarbeirosRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/pagamentos': typeof AuthenticatedAppPagamentosRoute
  '/_authenticated/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/_authenticated/app/servicos': typeof AuthenticatedAppServicosRoute
  '/api/whatsapp/status': typeof ApiWhatsappStatusRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/clientes/$id': typeof AuthenticatedAppClientesIdRoute
  '/api/public/hooks/automacoes': typeof ApiPublicHooksAutomacoesRoute
  '/_authenticated/app/clientes/': typeof AuthenticatedAppClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/meus-agendamentos'
    | '/app'
    | '/agendar/confirmacao'
    | '/agendar/'
    | '/app/agenda'
    | '/app/agendamentos'
    | '/app/barbeiros'
    | '/app/configuracoes'
    | '/app/pagamentos'
    | '/app/relatorios'
    | '/app/servicos'
    | '/api/whatsapp/status'
    | '/app/'
    | '/app/clientes/$id'
    | '/api/public/hooks/automacoes'
    | '/app/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/meus-agendamentos'
    | '/agendar/confirmacao'
    | '/agendar'
    | '/app/agenda'
    | '/app/agendamentos'
    | '/app/barbeiros'
    | '/app/configuracoes'
    | '/app/pagamentos'
    | '/app/relatorios'
    | '/app/servicos'
    | '/api/whatsapp/status'
    | '/app'
    | '/app/clientes/$id'
    | '/api/public/hooks/automacoes'
    | '/app/clientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/meus-agendamentos'
    | '/_authenticated/app'
    | '/agendar/confirmacao'
    | '/agendar/'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/agendamentos'
    | '/_authenticated/app/barbeiros'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/pagamentos'
    | '/_authenticated/app/relatorios'
    | '/_authenticated/app/servicos'
    | '/api/whatsapp/status'
    | '/_authenticated/app/'
    | '/_authenticated/app/clientes/$id'
    | '/api/public/hooks/automacoes'
    | '/_authenticated/app/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  MeusAgendamentosRoute: typeof MeusAgendamentosRoute
  AgendarConfirmacaoRoute: typeof AgendarConfirmacaoRoute
  AgendarIndexRoute: typeof AgendarIndexRoute
  ApiWhatsappStatusRoute: typeof ApiWhatsappStatusRoute
  ApiPublicHooksAutomacoesRoute: typeof ApiPublicHooksAutomacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-agendamentos': {
      id: '/meus-agendamentos'
      path: '/meus-agendamentos'
      fullPath: '/meus-agendamentos'
      preLoaderRoute: typeof MeusAgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/agendar/': {
      id: '/agendar/'
      path: '/agendar'
      fullPath: '/agendar/'
      preLoaderRoute: typeof AgendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/confirmacao': {
      id: '/agendar/confirmacao'
      path: '/agendar/confirmacao'
      fullPath: '/agendar/confirmacao'
      preLoaderRoute: typeof AgendarConfirmacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agendamentos': {
      id: '/_authenticated/app/agendamentos'
      path: '/agendamentos'
      fullPath: '/app/agendamentos'
      preLoaderRoute: typeof AuthenticatedAppAgendamentosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/barbeiros': {
      id: '/_authenticated/app/barbeiros'
      path: '/barbeiros'
      fullPath: '/app/barbeiros'
      preLoaderRoute: typeof AuthenticatedAppBarbeirosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pagamentos': {
      id: '/_authenticated/app/pagamentos'
      path: '/pagamentos'
      fullPath: '/app/pagamentos'
      preLoaderRoute: typeof AuthenticatedAppPagamentosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/relatorios': {
      id: '/_authenticated/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AuthenticatedAppRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/servicos': {
      id: '/_authenticated/app/servicos'
      path: '/servicos'
      fullPath: '/app/servicos'
      preLoaderRoute: typeof AuthenticatedAppServicosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/whatsapp/status': {
      id: '/api/whatsapp/status'
      path: '/api/whatsapp/status'
      fullPath: '/api/whatsapp/status'
      preLoaderRoute: typeof ApiWhatsappStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/clientes/': {
      id: '/_authenticated/app/clientes/'
      path: '/clientes'
      fullPath: '/app/clientes/'
      preLoaderRoute: typeof AuthenticatedAppClientesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/clientes/$id': {
      id: '/_authenticated/app/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/app/clientes/$id'
      preLoaderRoute: typeof AuthenticatedAppClientesIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/hooks/automacoes': {
      id: '/api/public/hooks/automacoes'
      path: '/api/public/hooks/automacoes'
      fullPath: '/api/public/hooks/automacoes'
      preLoaderRoute: typeof ApiPublicHooksAutomacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppAgendamentosRoute: typeof AuthenticatedAppAgendamentosRoute
  AuthenticatedAppBarbeirosRoute: typeof AuthenticatedAppBarbeirosRoute
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppPagamentosRoute: typeof AuthenticatedAppPagamentosRoute
  AuthenticatedAppRelatoriosRoute: typeof AuthenticatedAppRelatoriosRoute
  AuthenticatedAppServicosRoute: typeof AuthenticatedAppServicosRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppClientesIdRoute: typeof AuthenticatedAppClientesIdRoute
  AuthenticatedAppClientesIndexRoute: typeof AuthenticatedAppClientesIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppAgendamentosRoute: AuthenticatedAppAgendamentosRoute,
  AuthenticatedAppBarbeirosRoute: AuthenticatedAppBarbeirosRoute,
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppPagamentosRoute: AuthenticatedAppPagamentosRoute,
  AuthenticatedAppRelatoriosRoute: AuthenticatedAppRelatoriosRoute,
  AuthenticatedAppServicosRoute: AuthenticatedAppServicosRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppClientesIdRoute: AuthenticatedAppClientesIdRoute,
  AuthenticatedAppClientesIndexRoute: AuthenticatedAppClientesIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  MeusAgendamentosRoute: MeusAgendamentosRoute,
  AgendarConfirmacaoRoute: AgendarConfirmacaoRoute,
  AgendarIndexRoute: AgendarIndexRoute,
  ApiWhatsappStatusRoute: ApiWhatsappStatusRoute,
  ApiPublicHooksAutomacoesRoute: ApiPublicHooksAutomacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
